blank_issues_enabled: true

contact_links:
  - name: Hiero Discord
    url: https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/discord.md
    about: Please ask and answer questions here.
