# This workflow notifies the GFI support team when an issue is labeled as GFI Candidate.

name: Good First Issue Candidate Notification

on:
  issues:
    types:
      - labeled

permissions:
  issues: write
  contents: read

jobs:
  gfi_candidate_notify_team:
    runs-on: hl-sdk-py-lin-md
    if: contains(github.event.issue.labels.*.name, 'good first issue candidate')
    concurrency:
      group: gfi-candidate-${{ github.event.issue.number }}
      cancel-in-progress: false

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Notify team of GFI candidate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: ${{ github.repository_owner != 'hiero-ledger' }}
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd  #v8.0.0
        with:
          script: |
            const script = require('./.github/scripts/bot-gfi-candidate-notification.js');
            await script({ github, context });
