# This workflow notifies the GFI support team when an issue is labeled as GFI Candidate.

name: Good First Issue Candidate Notification

on:
  issues:
    types:
      - labeled

permissions:
  issues: write
  contents: read

jobs:
  gfi_candidate_notify_team:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'good first issue candidate')
    concurrency:
      group: gfi-candidate-${{ github.event.issue.number }}
      cancel-in-progress: false

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Notify team of GFI candidate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: ${{ github.repository_owner != 'hiero-ledger' }}
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd  #v8.0.0
        with:
          script: |
            const script = require('./.github/scripts/bot-gfi-candidate-notification.js');
            await script({ github, context });
