name: PR Check â€“ Broken Markdown Links

on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read

jobs:
  pr-check-broken-links:
    runs-on: hl-sdk-py-lin-md

    steps:
      - name: Harden runner (audit outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Check Markdown links
        uses: tcort/github-action-markdown-link-check@e7c7a18363c842693fadde5d41a3bd3573a7a225 # v1.1.2
        with:
          use-quiet-mode: 'yes'
          check-modified-files-only: 'yes'
          base-branch: 'main'
