name: Request triage review on beginner PRs

on:
  pull_request_target:
    types: [labeled]

  workflow_dispatch:
      inputs:
        dry_run:
          description: 'Dry run mode (no actual review requests will be made)'
          required: false
          default: 'true'

concurrency:
    group: request-triage-${{ github.event.pull_request.number }}
    cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write

jobs:
  request-triage:
    if: ${{ github.event.label && (github.event.label.name == 'Good First Issue' || github.event.label.name == 'Beginner') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Make script executable
        run: chmod +x .github/scripts/bot-pr-gfi-review-triage.sh

      - name: Request triage by comment
        run: .github/scripts/bot-pr-gfi-review-triage.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
