name: "Bot: Working On Comment"

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Log the run without making any changes'
        required: true
        default: "true"
        type: string

jobs:
  working-command:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/working'))
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    concurrency:
      group: working-command-${{ github.event.issue.number || github.run_id }}
      cancel-in-progress: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf3058034d60565886e8487e41f6a157127110 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@8e8c4832c3f1a3036bf690509a27e8346f33290d # v4.1.7

      - name: Handle /working command
        id: working
        uses: actions/github-script@ed59741695cf082c5b2938b25d19485747644318 # v7.0.1
        env:
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        with:
          script: |
            const handler = require('./.github/scripts/bot-working-on-comment.js')
            await handler({github, context})
